### ISSUE TITLE
About improving recognition rate

### ISSUE THREAD

**Issue by m1517** [kristiankoskimaki/vidupe#2]
Hello, this software is great.
I found a problem in use and hope to improve it.The beginning of the video were added  some AD, making the video different in length and impossible to scan for duplicate items. I suppose to add a button to  extract the image  from the end of video and compare it?            ^_^   thank you。

**Comment by Chrool** [comment]
The way I understand it it compares the whole group of screenshots (say 2x2) with another whole group. Could we add an option for the thumbnail generation and comparison to capture each individual screenshot by itself and compare it to other single screenshots? It would increase the processing exponentially but it seems like the thumbnail generation takes the most cpu time.

**Comment by kristiankoskimaki** [comment]
Good ideas, but having tested for a day I can now say that:
-CutEnds mode (comparing the first and last screen individually) from v1.21 finds much more matches than the old way of combining screens into a single image.
-None of the other thumbnail modes find more results so they are effectively useless now.
-Comparing just the first and last screens is enough, more than that never finds additional matches.
-Comparing every 12 screen from video1 with all 12 screens from video2 is indeed very slow and only finds a few additional false positives.

**Comment by m1517** [comment]
Hi, I've been using it for a while and I can really find more repetitions. I sorted out the videos that I couldn't find, and found that most of them were of different durations.

I learned ffmpeg and read your source code, but I don't understand C++. I just found that you use the percentage of movie duration to take screenshots. The problem is that for videos with different duration, the location of screenshots will be different, resulting in lower accuracy.

Through my test, using ffmpeg -sseof -60 can not be affected by the duration, and a picture can also be. Can you change the 1x1 option to this? I don't know if the modification is troublesome. Anyway, thank you! I only know Chinese, so I only write these。
